server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://3.235.170.15:5432/gis
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


